### ISSUE TITLE
How would you add ticks at garc fucnction?

### ISSUE THREAD

**Issue by Shubham17962022** [ponnhide/pyCircos#12]
I need to need to show values present on garc. Something similar to ticks

**Comment by ponnhide** [comment]
I'm sorry for the late response. Now, Pycircos doesn't provide such kinds of functions. 
If you want to add ticks on the Garc object, It would be best to make ticks by yourself using the `barplot` function.
However, I can agree with the importance of the function of drawing ticks, so that I will update the pyCircos package within a few weeks.
