### ISSUE TITLE
Locus labeling

### ISSUE THREAD

**Issue by hildemann** [ponnhide/pyCircos#4]
Hey, 

trying out this cool circos plots i figured it would be helpful to be able to label the specified locus in the plot. These plots would be perfect for a project of mine.
So i noticed the individual locusses can be given a name, but can this name be displayed in the actual plot then also?
Or could one  insert a legend in the corner of the plot, labeling all locusses by their color and name?

Because playing round with the tutorial script i could only change locus coordinates, color, but changing the name would still not show any name.

Thanks for advice, 

Valentin

**Comment by ponnhide** [comment]
Now, pyCircos doesn't provide a function to display labels for each locus. In fact, I was trying to add the function previously. However, labels composed of long names often generate overlapping with others or protruding from the range, so I irritated and removed the function... However, I can respect your suggestion so that I will implement simple labeling functions. 
Thank you for your valuable suggestion.

**Comment by bw2** [comment]
+1 for adding a way to label the chromosomes
